# Generated by Django 5.2.5 on 2025-08-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_no',
            field=models.CharField(),
        ),
    ]
