# Generated by Django 5.2.5 on 2025-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField()),
                ('department', models.CharField()),
            ],
        ),
    ]
